language: node_js
node_js:
- '7'
- '8'
sudo: required
services:
- mongodb
before_script:
- npm run build
after_success:
- npm run coveralls
deploy:
  skip_cleanup: true
  provider: npm
  email: info@molecuel.org
  api_key:
    secure: BjO8b/ol2P3CoOLgD05XAyQRyXgjqihTFnO7lknzNyZ8UDVdP61o5B05D5oYNFFxP3ixHdhAsTh3lwGLCno30sUr4wNCtlltayX8NpWTvgOQ0nhoUzkcJL1nqh/vqU0rQep6LxBs3+JPoRSjIyntcD73fPjKBXf6p+1hTSaP6H0=
  on:
    repo: molecuel/elements
