language: node_js
services:
  - mongodb
  - elasticsearch
node_js:
  - "10"
before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.2.deb && sudo dpkg -i --force-confnew elasticsearch-6.2.2.deb && sudo service elasticsearch restart
before_script:
  - sleep 30
