name: Node.js CI

on:
  [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    if: ${{!contains(github.event.head_commit.message, '[skip ci]')}}

    strategy:
      matrix:
        node-version: [10]
        mongodb-version: [3.4]
        elasticsearch: ["6.8-SNAPSHOT"]

    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: ${{ matrix.elasticsearch }}
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_PACKAGE_READ}}
      - run: npm test
